name: Deploy
on:
  pull_request:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
          matrix:
            node-version: [20]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up NODE ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install with NPM
      run: npm i
    - name: Fix install
      run: npm i @rollup/rollup-win32-x64-msvc
    - name: Test client with NPM
      run: npm run test --workspace=client
    - name: Build client with NPM
      run: npm run build --workspace=client
    - name: Test server with NPM
      run: npm run test --workspace=server
    - name: Test server E2E with NPM
      run: npm run test:e2e --workspace=server
    - name: Build server with NPM
      run: npm run build --workspace=server